name=HW827_PPG
version=1.0.2
author=Gevindu Wickramaarachchi
maintainer=Gevindu Wickramaarachchi
sentence=PPG filtering and heart-rate detection for HW-827 pulse sensor.
paragraph=Provides raw signal, baseline-corrected filtered PPG, differentiated signal, pulse markers, and filtered BPM using derivative zero-crossing detection.
category=Sensors
url= https://www.github.com/gevindu/HW827_PPG
architectures=*
includes=HW827_PPG.h
